// Generated by the gRPC protobuf plugin.
// If you make any local change, they will be lost.
// source: image_guide.proto
#ifndef GRPC_image_5fguide_2eproto__INCLUDED
#define GRPC_image_5fguide_2eproto__INCLUDED

#include "image_guide.pb.h"

#include <grpc++/support/async_stream.h>
#include <grpc++/impl/rpc_method.h>
#include <grpc++/impl/proto_utils.h>
#include <grpc++/impl/service_type.h>
#include <grpc++/support/async_unary_call.h>
#include <grpc++/support/status.h>
#include <grpc++/support/stub_options.h>
#include <grpc++/support/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class RpcService;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace imageguide {

class ImageGuide GRPC_FINAL {
 public:
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    std::unique_ptr< ::grpc::ClientWriterInterface< ::imageguide::Image>> SendImage(::grpc::ClientContext* context, ::imageguide::Response* response) {
      return std::unique_ptr< ::grpc::ClientWriterInterface< ::imageguide::Image>>(SendImageRaw(context, response));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::imageguide::Image>> AsyncSendImage(::grpc::ClientContext* context, ::imageguide::Response* response, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::imageguide::Image>>(AsyncSendImageRaw(context, response, cq, tag));
    }
  private:
    virtual ::grpc::ClientWriterInterface< ::imageguide::Image>* SendImageRaw(::grpc::ClientContext* context, ::imageguide::Response* response) = 0;
    virtual ::grpc::ClientAsyncWriterInterface< ::imageguide::Image>* AsyncSendImageRaw(::grpc::ClientContext* context, ::imageguide::Response* response, ::grpc::CompletionQueue* cq, void* tag) = 0;
  };
  class Stub GRPC_FINAL : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::Channel>& channel);
    std::unique_ptr< ::grpc::ClientWriter< ::imageguide::Image>> SendImage(::grpc::ClientContext* context, ::imageguide::Response* response) {
      return std::unique_ptr< ::grpc::ClientWriter< ::imageguide::Image>>(SendImageRaw(context, response));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriter< ::imageguide::Image>> AsyncSendImage(::grpc::ClientContext* context, ::imageguide::Response* response, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncWriter< ::imageguide::Image>>(AsyncSendImageRaw(context, response, cq, tag));
    }

   private:
    std::shared_ptr< ::grpc::Channel> channel_;
    ::grpc::ClientWriter< ::imageguide::Image>* SendImageRaw(::grpc::ClientContext* context, ::imageguide::Response* response) GRPC_OVERRIDE;
    ::grpc::ClientAsyncWriter< ::imageguide::Image>* AsyncSendImageRaw(::grpc::ClientContext* context, ::imageguide::Response* response, ::grpc::CompletionQueue* cq, void* tag) GRPC_OVERRIDE;
    const ::grpc::RpcMethod rpcmethod_SendImage_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::Channel>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::SynchronousService {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status SendImage(::grpc::ServerContext* context, ::grpc::ServerReader< ::imageguide::Image>* reader, ::imageguide::Response* response);
    ::grpc::RpcService* service() GRPC_OVERRIDE GRPC_FINAL;
   private:
    std::unique_ptr< ::grpc::RpcService> service_;
  };
  class AsyncService GRPC_FINAL : public ::grpc::AsynchronousService {
   public:
    explicit AsyncService();
    ~AsyncService() {};
    void RequestSendImage(::grpc::ServerContext* context, ::grpc::ServerAsyncReader< ::imageguide::Response, ::imageguide::Image>* reader, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag);
  };
};

}  // namespace imageguide


#endif  // GRPC_image_5fguide_2eproto__INCLUDED
